version: '3' #specifies the version of Docker Compose file format

services: # Define the services (containers) that make up your application 
  web1:
    build: .
    ports: 
      - "5005:5005" #ports the service port 5005 on the container
    volumes:  #Mount the current directory on the host to /app in the container.allowing for code change without re
      - .:/app
    environment:  #sets the environment variable flask_env to development inside the container
      FLASK_ENV: development

  web2:
    build: .
    ports: 
      - "4005:4005"
    volumes:
      - .:/app
    command: python connect.py 
    networks:
      - my_network

  web3:
    build: .
    ports:
      - "2001:2001"
    volumes:
      - .:/app
    networks:
      - my_network
    depends_on:
      - mongo

  mongo :
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - .:/data/db
    command: python mongoapp.py
    networks:
      - my_network
    
networks:
  my_network:
    driver: bridge